export type Product={id:string;slug:string;name:string;brand:string;category:string;price:number;compareAt?:number;rating:number;reviews:number;stock:number;image:string;badge?:string;description:string};
export const categories=[['skincare','Skincare','Daily rituals for a luminous complexion'],['makeup','Makeup','Polished colour, effortless confidence'],['haircare','Haircare','Care for every texture'],['fragrance','Fragrance','Memorable finishing notes'],['beauty-tools','Beauty Tools','Tools that elevate every ritual'],['body-care','Body Care','Comfort from head to toe'],['mens-care',"Men’s Care",'Modern essentials'],['gift-sets','Gift Sets','Beauty worth giving']];
export const products:Product[]=[
{id:'p1',slug:'radiance-vitamin-c-serum',name:'Radiance Vitamin C Serum',brand:'Éclat Atelier',category:'skincare',price:34,compareAt:42,rating:4.9,reviews:128,stock:18,image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80',badge:'Best seller',description:'A brightening daily serum with stable vitamin C and hyaluronic acid.'},
{id:'p2',slug:'velvet-skin-tint',name:'Velvet Skin Tint SPF 30',brand:'Lumière',category:'makeup',price:29,rating:4.8,reviews:86,stock:31,image:'https://images.unsplash.com/photo-1631730486574-4b7e0bfe0893?auto=format&fit=crop&w=900&q=80',badge:'New',description:'Breathable, buildable coverage with a natural skin finish.'},
{id:'p3',slug:'silk-repair-hair-oil',name:'Silk Repair Hair Oil',brand:'Neroli & Co.',category:'haircare',price:26,compareAt:31,rating:4.7,reviews:54,stock:9,image:'https://images.unsplash.com/photo-1626015365107-0a01b8ebef2d?auto=format&fit=crop&w=900&q=80',badge:'-16%',description:'Nourishing botanical oils for shine without weight.'},
{id:'p4',slug:'ambre-blanche-eau-de-parfum',name:'Ambre Blanche Eau de Parfum',brand:'Maison Serein',category:'fragrance',price:68,rating:4.9,reviews:42,stock:12,image:'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',badge:'Exclusive',description:'Soft amber, white florals and a warm, lasting trail.'},
{id:'p5',slug:'rose-quartz-facial-set',name:'Rose Quartz Facial Set',brand:'Rituel',category:'beauty-tools',price:38,rating:4.6,reviews:39,stock:22,image:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=80',description:'A cooling ritual set designed for a moment of calm.'},
{id:'p6',slug:'cashmere-body-cream',name:'Cashmere Body Cream',brand:'Éclat Atelier',category:'body-care',price:24,rating:4.8,reviews:75,stock:27,image:'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80',badge:'Trending',description:'Rich, comforting hydration with a subtle floral finish.'},
{id:'p7',slug:'daily-clarifying-cleanser',name:'Daily Clarifying Cleanser',brand:'Pure Form',category:'skincare',price:20,rating:4.7,reviews:64,stock:35,image:'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',description:'A gentle gel cleanser for balanced, fresh-feeling skin.'},
{id:'p8',slug:'soft-focus-blush',name:'Soft Focus Cream Blush',brand:'Lumière',category:'makeup',price:22,rating:4.9,reviews:101,stock:40,image:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',description:'Blendable colour with a healthy satin glow.'}
]; export const getProduct=(slug:string)=>products.find(p=>p.slug===slug);
